### ISSUE TITLE
Seems the WaterQuality.sim._model.setLinkPollut does not work on my case.

### ISSUE THREAD

**Issue by QianyangWang** [kLabUM/StormReactor#14]
Hi, I installed the StormReactor and tried to use it on my model, but it seems the water quality value didn't work correctly. Please see the code (I have four pollutants for my case):

with Simulation(r'D:\THCSOnewhydro\process1\thswmm\SWMM0806.inp') as sim:
    l = Links(sim)
    config  = {}
    for link in l:
        config[link.linkid] = {'type': 'link', 'pollutant': 'NH3-N', 'method': 'EventMeanConc', 'parameters': {'C': 10.0}}
    w1 = waterQuality(sim,config=config)
    for ind, step in enumerate(sim):
        if ind%20 == 0:
            #print(sim.current_time)
            c1 = l["cex17"].pollut_quality["NH3-N"]
            w1.updateWQState()
            c2 = l["cex17"].pollut_quality["NH3-N"]
            print(c1,c2)

Then the result was:
0.0 0.0
35.08007970905306 35.08007970905306
13.656991782750481 13.656991782750481
11.313829864947184 11.313829864947184
11.224691753331628 11.224691753331628
11.171458091432045 11.171458091432045
11.1569893720432 11.1569893720432
12.267327598668995 12.267327598668995
......

Thanks for the guidance!

**Comment by abhiramm7** [comment]
Hi @QianyangWang, Can you share your input file?

**Comment by QianyangWang** [comment]
> @QianyangWang, I can’t provide exact feedback for the issue you are having however, have you seen this video for using StormReactor?
> 
> https://youtu.be/cwrtF8RV3jU

Thanks, I have seen it, it worked on the official demo example but the same code didn't work on my model. I'll double check it.

**Comment by QianyangWang** [comment]
@abhiramm7 @bemcdonnell Ah, I've located the problem when preparing to send the input file. Seems it not the problem of the inp. The waterQuality.updateWQState() didn't work in the segment of the "if" sentence "if ind%20 == 0:"(see my code above). It worked when I deleted the judgement "if ind%20 == 0:".  Does It mean that the calculation step of the user defined water quality model is needed to be identical with the pyswmm routing step? I tried to add this judgement here because the calculation duration of the user defined water quality model was much more longer than the original model (although this effect makes sense since there are lots of interactions between the python and C codes), therefore I wanted to increase the water quality calculation time step.

**Comment by bemcdonnell** [comment]
@QianyangWang im sorry I have noticed that. Yes you are correct. When you’re assessing water quality, pyswmm needs to intervene every SWMM routing step to update the pollutants.  I edited StormReactor to throw an exception if a user was trying to use sim.step_advance(). I understand this does slow simulations down. This might be good to add to the documentation- would this be something you’d be willing to consider adding?  The other detail to note - if we wanted to hold constant a wq value, this is attainable if we make some edits to how we implemented this inside swmm. We could speed things up with some edits if you’d be open to collaborating!

**Comment by bemcdonnell** [comment]
@QianyangWang, can you post that over at pyswmm? We’re in planning stages for pyswmm-v2 right now. This will be useful there

**Comment by bemason** [comment]
> @QianyangWang im sorry I have noticed that. Yes you are correct. When you’re assessing water quality, pyswmm needs to intervene every SWMM routing step to update the pollutants. I edited StormReactor to throw an exception if a user was trying to use sim.step_advance(). I understand this does slow simulations down. This might be good to add to the documentation- would this be something you’d be willing to consider adding? The other detail to note - if we wanted to hold constant a wq value, this is attainable if we make some edits to how we implemented this inside swmm. We could speed things up with some edits if you’d be open to collaborating!

Hi all— I have been out of the country all week and am just starting to check emails at the airport. Has this issue been resolved/how can I assist?

**Comment by bemcdonnell** [comment]
@bemason I think @QianyangWang is just proposing a change in the documentation which would clarify to the user that they cannot skip time steps when using StormReactor.  As we plan pyswmm-v2, we can incorporate the pollut "settings" in SWMM so the values remain constant without the need for pyswmm to intervene each step.  However, for now, just like issue #11, it is probably worth editing the docs

**Comment by QianyangWang** [comment]
@bemason Thanks, the small issue has been located. I found that the time step of the water quality calculation should be identical with the flow routing step. When trying to skip time steps using StormReactor, it will be malfunctioned. This is not mentioned in the documentation and would be confusing when people try to skip some steps for a coarser WQ calculation.

**Comment by bemason** [comment]
Thank you @bemcdonnell and @QianyangWang. I have added a note on this to the [README.md](https://github.com/kLabUM/StormReactor/commit/9b3e700dea0c8321ac723e492f039e3f526bcfc5) file. I will now close this issue.
